version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "osrs-herb"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-ka7nlc6hsejl"
s3_prefix = "osrs-herb"
region = "us-east-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
